# Generated by Django 6.0.6 on 2026-07-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='seen',
            field=models.BooleanField(default=True),
        ),
    ]
