# Generated by Django 6.0.6 on 2026-09-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0002_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
