# Generated by Django 6.0.6 on 2026-09-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0003_cartitem_selected_options_orderitem_selected_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='fabric_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabric_color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
