# Generated by Django 6.0.6 on 2026-09-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0004_cartitem_fabric_color_orderitem_fabric_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='print_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='print_color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
