# Generated by Django 6.0.6 on 2026-06-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
