# Generated by Django 6.0.6 on 2026-06-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='variants',
            field=models.ManyToManyField(blank=True, help_text='اگه خالی بماند، این عکس به\u200cعنوان عکس پیش\u200cفرض/عمومی محصول استفاده می\u200cشود.', related_name='images', to='catalog.productvariant'),
        ),
    ]
