# Generated by Django 6.0.6 on 2026-06-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_related_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='related_products',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='related_variants',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='catalog.productvariant'),
        ),
    ]
