# Generated by Django 6.0.6 on 2026-06-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_product_related_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_designable',
            field=models.BooleanField(default=False),
        ),
    ]
