# Generated by Django 6.0.6 on 2026-06-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_is_designable'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_designable',
            field=models.BooleanField(default=False),
        ),
    ]
