# Generated by Django 6.0.6 on 2026-09-11 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_category_description_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('variant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VariantOptionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_modifier', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='catalog.variantoptiongroup')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('group', 'name')},
            },
        ),
    ]
