# Generated by Django 6.0.6 on 2026-09-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_variantoptiongroup_variantoptionchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
