# Generated by Django 6.0.6 on 2026-09-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_productvariant_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sales_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
