# Generated by Django 6.0.6 on 2026-09-20 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productvariant_sales_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=500)),
                ('primary_image', models.ImageField(upload_to='product_cards/%Y/%m/')),
                ('hover_image', models.ImageField(blank=True, null=True, upload_to='product_cards/%Y/%m/')),
                ('options', models.JSONField(blank=True, default=list)),
                ('price_from', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('price_to', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_cards', to='catalog.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
