# Generated by Django 6.0.6 on 2026-09-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_productcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='filter_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
