# Generated by Django 6.0.6 on 2026-10-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_productcard_filter_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price_table_axes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
